title = "TeXify3"
description = "TeXify3 - A LaTeX-style hugo theme with the gruvbox color scheme for personal blogging"
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> | 
Theme <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
keywords = ["hugo", "latex", "theme", "blog", "texify", "texify2", "texify3", "michael", "neuper"]
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
since = "2023"
toc = false
showWordCount = true
showReadingTime = true
rootFontSize = "100%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true

[commentEngine]
code = ""

[buymeacoffee]
code = ""

[sharingbuttons]
facebook = false
twitter = false
email = false
linkedin = false
reddit = false
whatsapp = false
hackernews = false
telegram = false
